const screens = {
  HOME: 0,
  FAVORITES: 1,
  HISTORY: 2,
  CHOOSE_BY_ATC: 3,
  CHOOSE_BY_THERAPEUTIC_GROUP: 4,
  CHOOSE_BY_PHARMACOLOGICAL_GROUP: 5,
  CHANGE_MEDICINE: 6,
};

export default screens;
